"""GitHub API helpers — fetch diffs, list files, create branches/commits/PRs."""

from __future__ import annotations

from typing import TYPE_CHECKING

from github import Github, GithubException

if TYPE_CHECKING:
    from github.Repository import Repository

from gemini_client import FileChange

BRANCH_PREFIX = "dependadocs/"
PR_LABEL = "documentation"
LAST_RUN_TAG = "dependadocs-last-run"
MAX_DIFF_BYTES = 512 * 1024  # 512 KB


def get_github_client(token: str) -> Github:
    return Github(token)


def get_pr_diff(repo: "Repository", pr_number: int) -> str:
    """Return a unified-diff-style string for all files changed in the PR."""
    pull = repo.get_pull(pr_number)
    files = pull.get_files()

    parts: list[str] = []
    for f in files:
        header = f"--- a/{f.filename}\n+++ b/{f.filename}\n"
        patch = f.patch or "(binary or empty file)"
        parts.append(header + patch)

    return "\n".join(parts)


def get_commit_diff(repo: "Repository", base_sha: str, head_sha: str) -> str:
    """Return a unified-diff-style string comparing base_sha to head_sha."""
    try:
        comparison = repo.compare(base_sha, head_sha)
    except GithubException as exc:
        print(f"[dependadocs] Warning: could not compare {base_sha[:7]}..{head_sha[:7]}: {exc}")
        return ""

    parts: list[str] = []
    total_bytes = 0
    truncated = False

    for f in comparison.files:
        header = f"--- a/{f.filename}\n+++ b/{f.filename}\n"
        patch = f.patch or "(binary or empty file)"
        chunk = header + patch
        chunk_bytes = len(chunk.encode("utf-8"))
        if total_bytes + chunk_bytes > MAX_DIFF_BYTES:
            truncated = True
            break
        parts.append(chunk)
        total_bytes += chunk_bytes

    if truncated:
        print(
            f"[dependadocs] Diff truncated at {total_bytes // 1024} KB "
            f"({len(parts)} files). Remaining files skipped."
        )

    return "\n".join(parts)


def get_scheduled_diff(repo: "Repository", default_branch: str) -> tuple[str, str]:
    """Return (diff, head_sha) for a scheduled or manual run.

    Uses the 'dependadocs-last-run' tag as the base if it exists,
    otherwise falls back to the oldest of the last 50 commits.
    """
    head_sha = repo.get_branch(default_branch).commit.sha

    try:
        tag_ref = repo.get_git_ref(f"tags/{LAST_RUN_TAG}")
        base_sha = tag_ref.object.sha
        # Dereference annotated tags to their commit SHA
        if tag_ref.object.type == "tag":
            tag_obj = repo.get_git_tag(base_sha)
            base_sha = tag_obj.object.sha
        print(f"[dependadocs] Diffing from last run ({base_sha[:7]}) to HEAD ({head_sha[:7]}).")
    except GithubException:
        print("[dependadocs] No 'dependadocs-last-run' tag found. Comparing last 50 commits.")
        commits = list(repo.get_commits(sha=default_branch))
        if len(commits) < 2:
            print("[dependadocs] Not enough commits to diff.")
            return "", head_sha
        base_sha = commits[min(49, len(commits) - 1)].sha

    if base_sha == head_sha:
        print("[dependadocs] No new commits since last run.")
        return "", head_sha

    diff = get_commit_diff(repo, base_sha, head_sha)
    return diff, head_sha


def update_last_run_tag(repo: "Repository", sha: str) -> None:
    """Create or update the 'dependadocs-last-run' lightweight tag."""
    ref_path = f"refs/tags/{LAST_RUN_TAG}"
    try:
        ref = repo.get_git_ref(f"tags/{LAST_RUN_TAG}")
        ref.edit(sha=sha, force=True)
        print(f"[dependadocs] Updated '{LAST_RUN_TAG}' tag to {sha[:7]}.")
    except GithubException:
        repo.create_git_ref(ref=ref_path, sha=sha)
        print(f"[dependadocs] Created '{LAST_RUN_TAG}' tag at {sha[:7]}.")


def create_doc_pr(
    repo: "Repository",
    base_ref: str,
    changes: list[FileChange],
    branch_suffix: str,
    pr_title: str,
    trigger_description: str,
) -> str:
    """Create a branch, commit doc changes, and open a PR.

    Returns the URL of the newly created PR.
    """
    branch_name = f"{BRANCH_PREFIX}{branch_suffix}"

    base_sha = repo.get_branch(base_ref).commit.sha
    _ensure_branch(repo, branch_name, base_sha)

    for change in changes:
        _upsert_file(repo, branch_name, change)

    body_lines = [
        "## Documentation update",
        "",
        f"Auto-generated by [Dependadocs](https://github.com/wwelsh/dependadocs) {trigger_description}.",
        "",
        "**Please review carefully before merging.** AI-generated content may contain errors.",
        "",
        "### Files updated",
    ]
    for change in changes:
        body_lines.append(f"- `{change.file}`: {change.reason}")

    _ensure_label(repo, PR_LABEL, "0075ca", "Documentation updates")

    pr = repo.create_pull(
        title=pr_title,
        body="\n".join(body_lines),
        head=branch_name,
        base=base_ref,
    )

    try:
        pr.add_to_labels(PR_LABEL)
    except GithubException as exc:
        print(f"[dependadocs] Warning: could not add label '{PR_LABEL}': {exc}")

    return pr.html_url


def _ensure_branch(repo: "Repository", branch_name: str, base_sha: str) -> None:
    """Create the branch if it doesn't exist; if it does, reset it to base_sha."""
    ref_path = f"refs/heads/{branch_name}"
    try:
        ref = repo.get_git_ref(f"heads/{branch_name}")
        ref.edit(sha=base_sha, force=True)
        print(f"[dependadocs] Reset existing branch '{branch_name}' to {base_sha[:7]}.")
    except GithubException:
        repo.create_git_ref(ref=ref_path, sha=base_sha)
        print(f"[dependadocs] Created branch '{branch_name}' at {base_sha[:7]}.")


def _upsert_file(repo: "Repository", branch: str, change: FileChange) -> None:
    """Create or update a file on the given branch."""
    content_bytes = change.updated_content.encode("utf-8")
    message = f"docs: update {change.file} ({change.reason[:72]})"

    try:
        existing = repo.get_contents(change.file, ref=branch)
        if isinstance(existing, list):
            existing = existing[0]
        repo.update_file(
            path=change.file,
            message=message,
            content=content_bytes,
            sha=existing.sha,
            branch=branch,
        )
        print(f"[dependadocs] Updated {change.file}.")
    except GithubException:
        repo.create_file(
            path=change.file,
            message=message,
            content=content_bytes,
            branch=branch,
        )
        print(f"[dependadocs] Created {change.file}.")


def _ensure_label(repo: "Repository", name: str, color: str, description: str) -> None:
    """Create the label if it doesn't exist already."""
    try:
        repo.get_label(name)
    except GithubException:
        try:
            repo.create_label(name=name, color=color, description=description)
        except GithubException as exc:
            print(f"[dependadocs] Warning: could not create label '{name}': {exc}")
