"""GitHub API helpers — fetch diffs, list files, create branches/commits/PRs."""

from __future__ import annotations

from typing import TYPE_CHECKING

from github import Github, GithubException

if TYPE_CHECKING:
    from github.Repository import Repository

from gemini_client import FileChange

BRANCH_PREFIX = "dependadocs/"
PR_LABEL = "documentation"
MAX_DIFF_BYTES = 512 * 1024  # 512 KB


def get_github_client(token: str) -> Github:
    return Github(token)


def get_pr_diff(repo: Repository, pr_number: int) -> str:
    """Return a unified-diff-style string for all files changed in the PR."""
    pull = repo.get_pull(pr_number)
    files = pull.get_files()

    parts: list[str] = []
    for f in files:
        header = f"--- a/{f.filename}\n+++ b/{f.filename}\n"
        patch = f.patch or "(binary or empty file)"
        parts.append(header + patch)

    return "\n".join(parts)


def get_commit_diff(repo: Repository, base_sha: str, head_sha: str) -> str:
    """Return a unified-diff-style string comparing base_sha to head_sha."""
    try:
        comparison = repo.compare(base_sha, head_sha)
    except GithubException as exc:
        print(f"[dependadocs] Warning: could not compare {base_sha[:7]}..{head_sha[:7]}: {exc}")
        return ""

    parts: list[str] = []
    total_bytes = 0
    truncated = False

    for f in comparison.files:
        header = f"--- a/{f.filename}\n+++ b/{f.filename}\n"
        patch = f.patch or "(binary or empty file)"
        chunk = header + patch
        chunk_bytes = len(chunk.encode("utf-8"))
        if total_bytes + chunk_bytes > MAX_DIFF_BYTES:
            truncated = True
            break
        parts.append(chunk)
        total_bytes += chunk_bytes

    if truncated:
        print(
            f"[dependadocs] Diff truncated at {total_bytes // 1024} KB "
            f"({len(parts)} files). Remaining files skipped."
        )

    return "\n".join(parts)


def get_scheduled_diff(repo: Repository, default_branch: str, lookback_days: int = 7) -> tuple[str, str]:
    """Return (diff, head_sha) for a scheduled or manual run.

    Diffs commits from the last `lookback_days` days against HEAD.
    """
    import datetime

    head_sha = repo.get_branch(default_branch).commit.sha
    since = datetime.datetime.now(datetime.UTC) - datetime.timedelta(days=lookback_days)

    commits = list(repo.get_commits(sha=default_branch, since=since))
    if not commits:
        print(f"[dependadocs] No commits in the last {lookback_days} day(s).")
        return "", head_sha

    base_sha = commits[-1].sha  # oldest commit in the window
    print(
        f"[dependadocs] Diffing last {lookback_days} day(s): "
        f"{base_sha[:7]}..{head_sha[:7]} ({len(commits)} commit(s))."
    )

    diff = get_commit_diff(repo, base_sha, head_sha)
    return diff, head_sha


def create_doc_pr(
    repo: Repository,
    base_ref: str,
    changes: list[FileChange],
    branch_suffix: str,
    pr_title: str,
    trigger_description: str,
) -> str:
    """Create a branch, commit doc changes, and open a PR.

    Returns the URL of the newly created PR.
    """
    branch_name = f"{BRANCH_PREFIX}{branch_suffix}"

    base_sha = repo.get_branch(base_ref).commit.sha
    _ensure_branch(repo, branch_name, base_sha)

    files_written = sum(1 for change in changes if _upsert_file(repo, branch_name, change))
    if files_written == 0:
        print("[dependadocs] No files changed after comparing content — skipping PR creation.")
        _delete_branch(repo, branch_name)
        return ""

    body_lines = [
        "## Documentation update",
        "",
        f"Auto-generated by [Dependadocs](https://github.com/usr-wwelsh/dependadocs) {trigger_description}.",
        "",
        "**Please review carefully before merging.** AI-generated content may contain errors.",
        "",
        "### Files updated",
    ]
    for change in changes:
        body_lines.append(f"- `{change.file}`: {change.reason}")

    _ensure_label(repo, PR_LABEL, "0075ca", "Documentation updates")

    pr = repo.create_pull(
        title=pr_title,
        body="\n".join(body_lines),
        head=branch_name,
        base=base_ref,
    )

    try:
        pr.add_to_labels(PR_LABEL)
    except GithubException as exc:
        print(f"[dependadocs] Warning: could not add label '{PR_LABEL}': {exc}")

    return pr.html_url


def _ensure_branch(repo: Repository, branch_name: str, base_sha: str) -> None:
    """Create the branch if it doesn't exist; if it does, reset it to base_sha."""
    ref_path = f"refs/heads/{branch_name}"
    try:
        ref = repo.get_git_ref(f"heads/{branch_name}")
        ref.edit(sha=base_sha, force=True)
        print(f"[dependadocs] Reset existing branch '{branch_name}' to {base_sha[:7]}.")
    except GithubException:
        repo.create_git_ref(ref=ref_path, sha=base_sha)
        print(f"[dependadocs] Created branch '{branch_name}' at {base_sha[:7]}.")


def _upsert_file(repo: Repository, branch: str, change: FileChange) -> bool:
    """Create or update a file on the given branch.

    Returns True if the file was written, False if content was unchanged.
    """
    content_bytes = change.updated_content.encode("utf-8")
    message = f"docs: update {change.file} ({change.reason[:72]})"

    try:
        existing = repo.get_contents(change.file, ref=branch)
        if isinstance(existing, list):
            existing = existing[0]
        if existing.decoded_content == content_bytes:
            print(f"[dependadocs] Skipped {change.file} (content unchanged).")
            return False
        repo.update_file(
            path=change.file,
            message=message,
            content=content_bytes,
            sha=existing.sha,
            branch=branch,
        )
        print(f"[dependadocs] Updated {change.file}.")
    except GithubException:
        repo.create_file(
            path=change.file,
            message=message,
            content=content_bytes,
            branch=branch,
        )
        print(f"[dependadocs] Created {change.file}.")
    return True


def _delete_branch(repo: Repository, branch_name: str) -> None:
    """Delete a branch ref, ignoring errors if it doesn't exist."""
    try:
        ref = repo.get_git_ref(f"heads/{branch_name}")
        ref.delete()
        print(f"[dependadocs] Deleted branch '{branch_name}'.")
    except GithubException as exc:
        print(f"[dependadocs] Warning: could not delete branch '{branch_name}': {exc}")


def _ensure_label(repo: Repository, name: str, color: str, description: str) -> None:
    """Create the label if it doesn't exist already."""
    try:
        repo.get_label(name)
    except GithubException:
        try:
            repo.create_label(name=name, color=color, description=description)
        except GithubException as exc:
            print(f"[dependadocs] Warning: could not create label '{name}': {exc}")
